In [ ]:
pip install numpy

In [ ]:
import numpy as np

In [ ]:
a = np.arange(6)  # 1D array
a.shape

(6,)

In [ ]:
a2 = a[np.newaxis,:]  # 2D array (1,6) 1 row, 6 Columns
print(a2)
a2.shape

[[0 1 2 3 4 5]]


(1, 6)

In [ ]:
a3 = a2[np.newaxis, :]  # 3D array x,y,z ,  1 Block , 1 rows, 6 columns
print(a3)
a3.shape

[[[0 1 2 3 4 5]]]


(1, 1, 6)

--------------------------------------------------------------------------------
# Creating Arrays With Numpy

In [ ]:
a = np.array([1,2,3,4,5,6])

In [ ]:
a = np.array([1,2,3,4,5,6,7])
b = np.array ([(1,2,3,4,5,6,7),(4,5,6,7,8,9,10)])

In [ ]:
a.shape

(7,)

In [ ]:
b.shape

(2, 7)

In [ ]:
type(a) # type of array

numpy.ndarray

In [ ]:
b.dtype # data type of array elements

dtype('int64')

In [ ]:
print(a)
a.shape

[1 2 3 4 5 6 7]


(7,)

In [ ]:
print(b)
b.shape

[[ 1  2  3  4  5  6  7]
 [ 4  5  6  7  8  9 10]]


(2, 7)

# initialize  arrays

In [ ]:
zeros = np.zeros((3,5))  # (Rows,columns)
print(zeros)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
zeros.dtype

dtype('float64')

In [ ]:
ones = np.ones((2,5))
print(ones)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
ones.dtype

dtype('float64')

In [ ]:
New = np.full((2,6),5.5)
print(New)

[[5.5 5.5 5.5 5.5 5.5 5.5]
 [5.5 5.5 5.5 5.5 5.5 5.5]]


In [ ]:
New.dtype

dtype('float64')

In [ ]:
identity = np.eye(4)   # Creating an identity matrix  4*4 hota hai
print(identity)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
identity.dtype

dtype('float64')

# Array Attributes

In [ ]:
a.shape  # shape of array

(7,)

In [ ]:
len(b)   # give us the length of array

2

In [ ]:
b.ndim  # give us the dimension of array

2

In [ ]:
b.size  # gives us the numbers of elements in array

14

In [ ]:
a.ndim

1

# Basic Operations

In [ ]:
a

array([1, 2, 3, 4, 5, 6, 7])

In [ ]:
b

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 4,  5,  6,  7,  8,  9, 10]])

In [ ]:
g = a - b  # subtraction
print(g)

[[ 0  0  0  0  0  0  0]
 [-3 -3 -3 -3 -3 -3 -3]]


In [ ]:
g = a + b   # Addition
print(g)

[[ 2  4  6  8 10 12 14]
 [ 5  7  9 11 13 15 17]]


In [ ]:
# another method
h1 = np.add(a,b)
h1

array([[ 2,  4,  6,  8, 10, 12, 14],
       [ 5,  7,  9, 11, 13, 15, 17]])

In [ ]:
# Multiplication
i = a * b
i

array([[ 1,  4,  9, 16, 25, 36, 49],
       [ 4, 10, 18, 28, 40, 54, 70]])

In [ ]:
# Division
j = a / b
j

array([[1.        , 1.        , 1.        , 1.        , 1.        ,
        1.        , 1.        ],
       [0.25      , 0.4       , 0.5       , 0.57142857, 0.625     ,
        0.66666667, 0.7       ]])

In [ ]:
a

array([1, 2, 3, 4, 5, 6, 7])

In [ ]:
# Square of each element
k = a ** 2
k

array([ 1,  4,  9, 16, 25, 36, 49])

--------------------------------------------------------------------------------
# Numpy (Part-2)

In [ ]:
import numpy as np

In [ ]:
empty = np.empty((3,4))
print(empty)
print('-----------------------------------')
print(empty[1])

[[5.5 5.5 5.5 5.5]
 [5.5 5.5 5.5 5.5]
 [5.5 5.5 5.5 5.5]]
-----------------------------------
[5.5 5.5 5.5 5.5]


In [ ]:
x = np.arange(6)
x

array([0, 1, 2, 3, 4, 5])

In [ ]:
# Array of Even Numbers from 0 to 22
even = np.arange(0,22,2)
print(even)

[ 0  2  4  6  8 10 12 14 16 18 20]


In [ ]:
# Array of odd number from 0 to 23
odd = np.arange(1,23,2)
print(odd)

[ 1  3  5  7  9 11 13 15 17 19 21]


In [ ]:
# specific differnce between number
diff = np.arange(0,25,5)
print(diff)

[ 0  5 10 15 20]


In [ ]:
lin = np.linspace(1,20,12)
print(lin)

[ 1.          2.72727273  4.45454545  6.18181818  7.90909091  9.63636364
 11.36363636 13.09090909 14.81818182 16.54545455 18.27272727 20.        ]


In [ ]:
lin.dtype

dtype('float64')

In [ ]:
# difine the dtype of array
x = np.arange(0,22.6,1.5, dtype=np.int64)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [ ]:
# Sorting an array
arr = np.array([2,1,5,3,7,4,6,8])
arr

array([2, 1, 5, 3, 7, 4, 6, 8])

In [ ]:
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])

In [ ]:
# concatenate these array
c = np.concatenate((a,b))
c

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

# Concatenate 2D Arrays

In [ ]:
x = np.array([[1,2], [3,4]])  # 2x2 Array
y = np.array([[5,6]])  # 1x2 Array


In [ ]:
x

array([[1, 2],
       [3, 4]])

In [ ]:
y

array([[5, 6]])

In [ ]:
# Concatenate 2D Arrays
z = np.concatenate((x,y),axis=0)
z

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
w = np.array([[5,1],[7,1]]) # 2x2 Array
x = np.array([[1,2],[3,4]]) # 2x2 Array

In [ ]:
w

array([[5, 1],
       [7, 1]])

In [ ]:
x

array([[1, 2],
       [3, 4]])

In [ ]:
z1 = np.concatenate((w,x), axis=1)
z1

array([[5, 1, 1, 2],
       [7, 1, 3, 4]])

In [ ]:
# craete 3D array
array_example = np.array([[[0,1,2,3],
                           [4,5,6,7]],

                           [[0,1,2,3],
                            [4,5,6,7]],

                           [[0,1,2,3],
                            [4,5,6,7]]])

array_example.ndim

3

In [ ]:
len(array_example)

3

In [ ]:
array_example.size

24

In [ ]:
array_example.shape

(3, 2, 4)

In [ ]:
array_example.dtype

dtype('int64')

In [ ]:
# create 3D array of size (3,1,4)
a1 = np.array([[[0,1,2,3]],
                       [[4,5,6,7]],
                       [[0,1,2,3]]])

a1.shape

(3, 1, 4)

In [ ]:
# reshape the a
a2 = a1.reshape(6,2)
a2.shape

(6, 2)

In [ ]:
a2

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [0, 1],
       [2, 3]])

In [ ]:
a2.reshape(3,1,4)

array([[[0, 1, 2, 3]],

       [[4, 5, 6, 7]],

       [[0, 1, 2, 3]]])

In [ ]:
# create a 1D array
a = np.array([1,2,3,4,5,6,7,8])
a.shape

(8,)

In [ ]:
# convert that into 2D array
a[np.newaxis, :].shape
a.shape
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
c = a[: , np.newaxis]
c.shape
c


array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

# Indexing and slicing

In [ ]:
a = np.array([1,2,3,4,5,6,7,8])
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
a[2]

3

In [ ]:
a[2:5]

array([3, 4, 5])

In [ ]:
a[-4:]

array([5, 6, 7, 8])

In [ ]:
a[1:]

array([2, 3, 4, 5, 6, 7, 8])

In [ ]:
b = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
b[0]

array([1, 2, 3, 4])

In [ ]:
b [b < 5]

array([1, 2, 3, 4])

In [ ]:
b [b >= 10]

array([10, 11, 12])

In [ ]:
b[b % 2 == 0]  # filter even number

array([ 2,  4,  6,  8, 10, 12])

In [ ]:
b[b % 2 == 1]  # filter odd number

array([ 1,  3,  5,  7,  9, 11])

In [ ]:
# Use two Conditions
b[(b > 2) & (b < 11)]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
# Use theree Conditions and filter the arrays
b[(b > 2) & (b < 11) & (b % 2 == 0)]

array([ 4,  6,  8, 10])

In [ ]:
b [(b > 2) | (b < 11) ]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

# Numpy indexing and Slicing

In [ ]:
import numpy as np

In [ ]:
# Create an array
a = np.array([1,2,3,4,5,6,7])
a

array([1, 2, 3, 4, 5, 6, 7])

In [ ]:
b = np.arange(0,12,2)
b

array([ 0,  2,  4,  6,  8, 10])

In [ ]:
b[2]

4

In [ ]:
# convert to Rows & columns
c = b.reshape(2,3)
c

array([[ 0,  2,  4],
       [ 6,  8, 10]])

In [ ]:
c [0]

array([0, 2, 4])

# Enlists boolean Operators Conditional operators

--------------------------------------------------------------------------------
# Making an array from a data or another array

In [ ]:
a = np.arange(0,222,5)
a

array([  0,   5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,
        65,  70,  75,  80,  85,  90,  95, 100, 105, 110, 115, 120, 125,
       130, 135, 140, 145, 150, 155, 160, 165, 170, 175, 180, 185, 190,
       195, 200, 205, 210, 215, 220])

In [ ]:
len(a)

45

In [ ]:
array1 = a[40:45]
array1

array([200, 205, 210, 215, 220])

In [ ]:
a = np.array([1,2,3,4,5,6,7])
b = np.array([8,9,10,11,12,13,14])

In [ ]:
c = np.vstack((a,b))
c

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [ ]:
d = np.hstack((a,b))
d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
d = d.reshape(2,7)
d

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

# Matrix or Matrices

In [ ]:
# create a 2x3 matrix
a = np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
# ceate a matrix of big dimension
b = np.arange(0,100,2).reshape(5,10)
b

array([[ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28, 30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48, 50, 52, 54, 56, 58],
       [60, 62, 64, 66, 68, 70, 72, 74, 76, 78],
       [80, 82, 84, 86, 88, 90, 92, 94, 96, 98]])

In [ ]:
# Slicing a matrix of 3X2
b[0:3 , 3:5] # 0 Row , 3 columns, size 0f element 3, size of columns 5

array([[ 6,  8],
       [26, 28],
       [46, 48]])

In [ ]:
b.max()

98

In [ ]:
b.min()

0

In [ ]:
b.sum()

2450

In [ ]:
b.max(axis =0) # only for Rows

array([80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [ ]:
b.min(axis =0)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
b.max(axis =1)  # only for column

array([18, 38, 58, 78, 98])

In [ ]:
b.min(axis = 1)

array([ 0, 20, 40, 60, 80])

In [ ]:
m = np.arange(0,20,2).reshape(5,2)
m

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10],
       [12, 14],
       [16, 18]])

In [ ]:
m + np.array([20,22])

array([[20, 24],
       [24, 28],
       [28, 32],
       [32, 36],
       [36, 40]])

In [ ]:
np.vstack((m, np.array([42,44])))

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10],
       [12, 14],
       [16, 18],
       [42, 44]])

In [ ]:
b

array([[ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28, 30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48, 50, 52, 54, 56, 58],
       [60, 62, 64, 66, 68, 70, 72, 74, 76, 78],
       [80, 82, 84, 86, 88, 90, 92, 94, 96, 98]])

In [ ]:
np.flip(b)

array([[98, 96, 94, 92, 90, 88, 86, 84, 82, 80],
       [78, 76, 74, 72, 70, 68, 66, 64, 62, 60],
       [58, 56, 54, 52, 50, 48, 46, 44, 42, 40],
       [38, 36, 34, 32, 30, 28, 26, 24, 22, 20],
       [18, 16, 14, 12, 10,  8,  6,  4,  2,  0]])